"""
This type stub file was generated by pyright.
"""

"""
molvs.utils
~~~~~~~~~~~

This module contains miscellaneous utility functions.

:copyright: Copyright 2016 by Matt Swain.
:license: MIT, see LICENSE file for more details.
"""
def memoized_property(fget): # -> property:
    """Decorator to create memoized properties."""
    ...

def pairwise(iterable): # -> zip[Tuple[Unknown, Unknown]]:
    """Utility function to iterate in a pairwise fashion."""
    ...

