"""
This type stub file was generated by pyright.
"""

""" Basic EState definitions

"""
def GetPrincipleQuantumNumber(atNum): # -> Literal[1, 2, 3, 4, 5, 6, 7]:
  """ Get principal quantum number for atom number """
  ...

def EStateIndices(mol, force=...): # -> Any:
  """ returns a tuple of EState indices for the molecule

    Reference: Hall, Mohney and Kier. JCICS _31_ 76-81 (1991)

  """
  ...

def MaxEStateIndex(mol, force=...): # -> Any:
  ...

def MinEStateIndex(mol, force=...): # -> Any:
  ...

def MaxAbsEStateIndex(mol, force=...): # -> Any:
  ...

def MinAbsEStateIndex(mol, force=...): # -> Any:
  ...

if __name__ == '__main__':
  ...
