"""
This type stub file was generated by pyright.
"""

"""Code common to all toolkits"""
def detect_secondary_structure(res_dict):
    """Detect alpha helices and beta sheets in res_dict by phi and psi angles"""
    ...

def canonize_ring_path(path): # -> list[Unknown]:
    """Make a canonic path - list of consecutive atom IDXs bonded in a ring
    sorted in an uniform fasion.
        1) Move the smallest index to position 0
        2) Look for the smallest first step (delta IDX)
        3) Ff -1 is smallest, inverse the path and move min IDX to position 0

    Parameters
    ----------
    path : list of integers
        A list of consecutive atom indices in a ring

    Returns
    -------
    canonic_path : list of integers
        Sorted list of atoms
    """
    ...

