"""
This type stub file was generated by pyright.
"""

from .fps import *
from .edge_coarsening import *

"""The ``dgl.geometry`` package contains geometry operations:

* Farthest point sampling for point cloud sampling

* Neighbor matching module for graclus pooling

.. note::
    This package is experimental and the interfaces may be subject
    to changes in future releases.
"""
