# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: $(BuildID)

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install development dependencies'

  - script: |
      flake8 .
    displayName: 'Run lint tests'

  - script: |
      python -m pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install development dependencies'

  - script: sed -i "s/'$/.dev$(Build.BuildNumber)'/g" chemmltoolkit/__version__.py
    displayName: 'Update version string'

  - script: python setup.py sdist bdist_wheel
    displayName: 'Build project'

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: 'ChemMLToolkit'
      externalFeeds: 'PyPi-Upload'
    displayName: Add twine credentials

  - script: |
      twine upload -r ChemMLToolkit --config-file $(PYPIRC_PATH) dist/*
      twine upload -r PyPi-Upload --config-file $(PYPIRC_PATH) dist/*
    displayName: Publish to Azure Artifacts
