# A conda environment file for building and testing the ChemMLToolkit

name: chemmltoolkit
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - tensorflow>=2.0
  - rdkit
  - biopython
  - openbabel
  - oddt
  - flake8
  - pytest
  - pytest-cov
  - wheel
  - twine
