"""
This type stub file was generated by pyright.
"""

""" Supplies an abstract class for working with sequences of molecules

"""
class MolSupplier:
  """ we must, at minimum, support forward iteration

  """
  def __init__(self) -> None:
    ...
  
  def Reset(self): # -> None:
    ...
  
  def __iter__(self): # -> MolSupplier:
    ...
  
  def next(self):
    ...
  
  def NextMol(self): # -> None:
    """   Must be implemented in child class

    """
    ...
  
  __next__ = ...


