# A conda environment file for building and testing the ChemMLToolkit

name: dev-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - tensorflow>=2.0
  - rdkit
  - flake8
  - pytest
  - pytest-cov
  - wheel
  - twine
