# A conda environment file for building and testing the ChemMLToolkit

name: dev-environment
channels:
  - rdkit
dependencies:
  - python=3.6
  - pandas
  - rdkit
  - flake8
  - pytest
  - pytest-cov
  - wheel
  - twine
  - pip:
    - tensorflow==2.0.0-alpha
