"""
This type stub file was generated by pyright.
"""

import sys
import warnings
from . import openbabel

__version__ = ...
_thismodule = ...
class OBProxy:
    def __getattr__(self, name): # -> Any:
        ...
    


