"""
This type stub file was generated by pyright.
"""

import ctypes

"""Runtime NDArray api"""
DGLPyCapsuleDestructor = ...
_c_str_dltensor = ...
_c_str_used_dltensor = ...
if hasattr(ctypes, 'pythonapi'):
    ...
_c_dlpack_deleter = ...
class NDArrayBase:
    """A simple Device/CPU Array object in runtime."""
    __slots__ = ...
    def __init__(self, handle, is_view=...) -> None:
        """Initialize the function with handle

        Parameters
        ----------
        handle : DGLArrayHandle
            the handle to the underlying C++ DGLArray
        """
        ...
    
    def __del__(self): # -> None:
        ...
    
    def to_dlpack(self, alignment=...): # -> Any:
        """Produce an array from a DLPack Tensor without copying memory

        Args
        -------
        alignment: int, default to be 0
        Indicates the alignment requirement when converting to dlpack. Will copy to a
        new tensor if the alignment requirement is not satisfied.
        0 means no alignment requirement.


        Returns
        -------
        dlpack : DLPack tensor view of the array data
        """
        ...
    


_DGL_COMPATS = ...
_CLASS_NDARRAY = ...
