"""
This type stub file was generated by pyright.
"""

import ctypes

"""ctypes object API."""
ObjectHandle = ctypes.c_void_p
__init_by_constructor__ = ...
OBJECT_TYPE = ...
class ObjectBase:
    """Object base class"""
    __slots__ = ...
    def __del__(self): # -> None:
        ...
    
    def __getattr__(self, name): # -> c_void_p | bytearray:
        ...
    
    def __init_handle_by_constructor__(self, fconstructor, *args): # -> None:
        """Initialize the handle by calling constructor function.

        Parameters
        ----------
        fconstructor : Function
            Constructor function.

        args: list of objects
            The arguments to the constructor

        Note
        ----
        We have a special calling convention to call constructor functions.
        So the return handle is directly set into the Object object
        instead of creating a new Object.
        """
        ...
    


