"""
This type stub file was generated by pyright.
"""

from rdkit.Chem.Draw.canvasbase import CanvasBase

faceMap = ...
def convertColor(color): # -> tuple[int, int, int]:
  ...

class Canvas(CanvasBase):
  fontScale = ...
  def __init__(self, img=..., imageType=..., fileName=..., size=...) -> None:
    ...
  
  def addCanvasLine(self, p1, p2, color=..., color2=..., **kwargs): # -> None:
    ...
  
  def addCanvasText(self, text, pos, font, color=..., **kwargs): # -> tuple[Unknown | float, Unknown | float, Unknown]:
    ...
  
  def addCanvasPolygon(self, ps, color=..., fill=..., stroke=..., **kwargs): # -> None:
    ...
  
  def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2=..., **kwargs): # -> None:
    ...
  
  def flush(self): # -> None:
    ...
  


