"""
This type stub file was generated by pyright.
"""

class CanvasBase:
  """Base class for specialized canvas backends"""
  def addCanvasLine(self, p1, p2, color=..., color2=..., **kwargs):
    """Draw a single line on the canvas

            This function will draw a line between `p1` and `p2` with the
            given `color`.
            If `color2` is specified, it will be used to draw the second half
            of the segment
        """
    ...
  
  def addCanvasText(self, text, pos, font, color=..., **kwargs):
    """Draw some text

           The provided `text` is drawn at position `pos` using the given
           `font` and the chosen `color`.
        """
    ...
  
  def addCanvasPolygon(self, ps, color=..., **kwargs):
    """Draw a polygon

           Draw a polygon identified by vertexes given in `ps` using
           the given `color`
        """
    ...
  
  def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2=..., **kwargs):
    """Draw a dashed wedge

           The wedge is identified by the three points `p1`, `p2`, and `p3`.
           It will be drawn using the given `color`; if `color2` is specified
           it will be used for the second half of the wedge

           TODO: fix comment, I'm not sure what `dash` does

        """
    ...
  
  def flush(self):
    """Complete any remaining draw operation

           This is supposed to be the last operation on the canvas before
           saving it
        """
    ...
  


