"""
This type stub file was generated by pyright.
"""

from rdkit.Chem.Draw.canvasbase import CanvasBase

class Canvas(CanvasBase):
  def __init__(self, size) -> None:
    ...
  
  def addCanvasLine(self, p1, p2, color=..., color2=..., **kwargs): # -> None:
    ...
  
  def addCanvasText(self, text, pos, font, color=..., **kwargs): # -> tuple[Unknown, Unknown, Literal[0]]:
    ...
  
  def addCanvasPolygon(self, ps, color=..., fill=..., stroke=..., **kwargs): # -> None:
    ...
  
  def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2=..., **kwargs): # -> None:
    ...
  
  def flush(self): # -> None:
    ...
  


