"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from . import citation_graph as citegrh
from .citation_graph import CitationGraphDataset, CiteseerGraphDataset, CoraBinary, CoraGraphDataset, PubmedGraphDataset
from .minigc import *
from .tree import SST, SSTDataset
from .utils import *
from .sbm import SBMMixture, SBMMixtureDataset
from .reddit import RedditDataset
from .ppi import LegacyPPIDataset, PPIDataset
from .tu import LegacyTUDataset, TUDataset
from .gnn_benchmark import AmazonCoBuy, AmazonCoBuyComputerDataset, AmazonCoBuyPhotoDataset, Coauthor, CoauthorCSDataset, CoauthorPhysicsDataset, CoraFull, CoraFullDataset
from .karate import KarateClub, KarateClubDataset
from .gindt import GINDataset
from .bitcoinotc import BitcoinOTC, BitcoinOTCDataset
from .gdelt import GDELT, GDELTDataset
from .icews18 import ICEWS18, ICEWS18Dataset
from .qm7b import QM7b, QM7bDataset
from .qm9 import QM9, QM9Dataset
from .qm9_edge import QM9Edge, QM9EdgeDataset
from .dgl_dataset import DGLBuiltinDataset, DGLDataset
from .knowledge_graph import FB15k237Dataset, FB15kDataset, WN18Dataset
from .rdf import AIFBDataset, AMDataset, BGSDataset, MUTAGDataset
from .fraud import FraudAmazonDataset, FraudDataset, FraudYelpDataset
from .fakenews import FakeNewsDataset

"""The ``dgl.data`` package contains datasets hosted by DGL and also utilities
for downloading, processing, saving and loading data from external resources.
"""
def register_data_args(parser): # -> None:
    ...

def load_data(args): # -> CoraGraphDataset | CiteseerGraphDataset | PubmedGraphDataset | RedditDataset:
    ...

