"""
This type stub file was generated by pyright.
"""

"""For Tensor Serialization"""
__all__ = ['save_tensors', "load_tensors"]
def save_tensors(filename, tensor_dict):
    """
    Save dict of tensors to file
    
    Parameters
    ----------
    filename : str
        File name to store dict of tensors. 
    tensor_dict: dict of dgl NDArray or backend tensor
        Python dict using string as key and tensor as value

    Returns
    ----------
    status : bool
        Return whether save operation succeeds
    """
    ...

def load_tensors(filename, return_dgl_ndarray=...): # -> dict[Unknown, Unknown]:
    """
    load dict of tensors from file
    
    Parameters
    ----------
    filename : str
        File name to load dict of tensors. 
    return_dgl_ndarray: bool
        Whether return dict of dgl NDArrays or backend tensors

    Returns
    ---------
    tensor_dict : dict
        dict of tensor or ndarray based on return_dgl_ndarray flag
    """
    ...

