"""
This type stub file was generated by pyright.
"""

@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


D: <Expression>
A: <Expression>
I: <Expression>
Y: <Expression>
