"""
This type stub file was generated by pyright.
"""

'''
Collection of utilities to be used with descriptors

'''
def setDescriptorVersion(version=...): # -> (func: Unknown) -> Unknown:
   """ Set the version on the descriptor function.

  Use as a decorator """
   ...

class VectorDescriptorNamespace(dict):
   def __init__(self, **kwargs) -> None:
      ...
   


class VectorDescriptorWrapper:
   """Wrap a function that returns a vector and make it seem like there
    is one function for each entry.  These functions are added to the global
    namespace with the names provided"""
   def __init__(self, func, names, version, namespace) -> None:
      ...
   
   def call_desc(self, mol, index): # -> Any | float:
      ...
   


