"""
This type stub file was generated by pyright.
"""

"""DGL mini-runtime."""
class Runtime:
    """The mini runtime class."""
    @staticmethod
    def run(prog): # -> None:
        """Run the given program."""
        ...
    


