"""
This type stub file was generated by pyright.
"""

from Bio.PDB.mmtf.DefaultParser import StructureDecoder
from .mmtfio import MMTFIO

"""Support for loading 3D structures stored in MMTF files."""
def get_from_decoded(decoder): # -> Structure:
    """Return structure from decoder."""
    ...

class MMTFParser:
    """Class to get a Biopython structure from a URL or a filename."""
    @staticmethod
    def get_structure_from_url(pdb_id): # -> Structure:
        """Get a structure from a URL - given a PDB id.

        :param pdb_id: the input PDB id
        :return: the structure

        """
        ...
    
    @staticmethod
    def get_structure(file_path): # -> Structure:
        """Get a structure from a file - given a file path.

        :param file_path: the input file path
        :return: the structure

        """
        ...
    


