name: Python packaging and tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Initialise conda
      run: |
        conda init bash
    - name: Setup conda environment
      run: |
        conda env create --quiet --file environments/dev-environment-37.yml
        conda activate dev-environment
    - name: Check conda environment
      run: |
        conda env list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=chemmltoolkit --cov-report=xml --cov-report=html
